name: CI

on:
  push:
    branches:
    - main
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Run coverage
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3